# definition
direction: right
classes: {
  endpoint: {
    shape: circle
    style: {
      stroke-width: 0
      fill: "#44C7B1"
      shadow: true
    }
  }
}
**.style.border-radius: 5
start.class: endpoint
end.class: endpoint


# workflow
start -> get_string
get_string -> get_number
get_number -> number_not_empty

number_not_empty -> is_divisible_by_5: đúng
is_divisible_by_5 -> return_number: đúng
return_number -> end

is_divisible_by_5 -> remove_last_digit: sai
remove_last_digit -> number_not_empty

number_not_empty -> return_none: sai
return_none -> end


# labels
get_string: lấy chuỗi
get_number: lấy string number\n từ chuỗi
number_not_empty: {
    shape: diamond
    label: while number\nis not empty
}
is_divisible_by_5: {
    shape: diamond
    label: nếu int(number) % 5 == 0
}
return_number: trả về number
return_none: trả về None
remove_last_digit: xoá chữ số cuối cùng\ncủa number
